apiVersion: v1
kind: PersistentVolume
metadata:
  name: drone
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.123.142
    path: /home/shitangdama/data/