apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-default-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kbr1990117@gmail.com
    privateKeySecretRef:
      name: letsencrypt-default-prod
    http01: {}