replicaCount: 1

image:
  repository: registry.shitangdama.cn/test/demo
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: 
  - name: registrykey
nameOverride: "deployment-test"
fullnameOverride: "deployment-test"
instanceOverride: "deployment-test"
containerPort: 8080

service:
  type: ClusterIP
  targetPort: 8080
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/issuer: "letsencrypt-default-prod"
    certmanager.k8s.io/acme-challenge-type: http01
  hosts:
    - host: test.shitangdama.cn
      paths:
        - path: /
          port: 80
  tls:
    hosts:
      - test.shitangdama.cn
    secretName: deployment-test

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
