apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod #是我们创建的签发机构的名称，后面我们创建证书的时候会引用它
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory #是 acme 协议的服务端，我们这里用 Let’s Encrypt，这个地址就写死成这样就行
    email: kbr1990117@gmail.com #是你自己的邮箱，证书快过期的时候会有邮件提醒，不过 cert-manager 会利用 acme 协议自动给我们重新颁发证书来续期
    privateKeySecretRef:
      name: letsencrypt-prod #指示此签发机构的私钥将要存储到哪个 Secret 对象中，名称不重要
    http01: {} #这里指示签发机构使用 HTTP-01 的方式进行 acme 协议 (还可以用 DNS 方式，acme 协议的目的是证明这台机器和域名都是属于你的，然后才准许给你颁发证书)