apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
kubernetesVersion: v1.15.1
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  certSANs:
  - shitangdama.cn
  - "*.shitangdama.cn"
controllerManagerExtraArgs:
  address: 0.0.0.0
schedulerExtraArgs:
  address: 0.0.0.0