apiVersion:  cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: kube-system
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kbr1990117@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}