# apiVersion: v1
# kind: Namespace
# metadata:
#   name: drone
#   labels:
#     app.kubernetes.io/name: drone
#     app.kubernetes.io/part-of: drone
# ---

# kind: Deployment
# apiVersion: apps/v1
# metadata:
#   labels:
#     k8s-app: drone-runner
#   name: drone-runner
#   namespace: drone
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       k8s-app: drone-runner
#   template:
#     metadata:
#       labels:
#         k8s-app: drone-runner
#     spec:
#       containers:
#       - name: drone-runner
#         image: drone/drone-runner-kube:latest
#         ports:
#         - containerPort: 3000
#         env:
#         - name: DRONE_RPC_HOST
#           value: drone.shitangdama.cn
#         - name: DRONE_RPC_PROTO
#           value: https
#         - name: DRONE_RPC_SECRET
#           value: "1234"
#       nodeSelector:
#         kubernetes.io/hostname: node1

apiVersion: v1
kind: Pod
metadata:
  name: drone
spec:
  containers:
  - name: runner
    image: drone/drone-runner-kube:latest
    ports:
    - containerPort: 3000
    env:
    - name: DRONE_RPC_HOST
      value: drone.shitangdama.cn
    - name: DRONE_RPC_PROTO
      value: https
    - name: DRONE_RPC_SECRET
      value: "1234"