apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.123.142
    path: /home/shitangdama/data/